### ISSUE TITLE
"Инструктаж" прохождения теста

### ISSUE THREAD

**Issue by AnnaNebuko** [Duckest/Duckest#33]
[ПередТестом.docx](https://github.com/Duckest/Duckest/files/6259165/default.docx)

**Comment by kat9898** [comment]
![image](https://user-images.githubusercontent.com/39970318/113776456-9f32d600-9732-11eb-9fd2-ed0f2005b4ab.png)
сделала чуть меньше текста, а то было слишком перегружено
